### ISSUE TITLE
Move this repository under Paneron org

### ISSUE THREAD

**Issue by strogonoff** [paneron/convertors#9]
These convertors are not only for Glossarist anymore, they are applicable to other types of Paneron datasets too now.

- [x] This repository should be moved under `paneron` org
- [x] The domain should be moved to `convert.paneron.org` 

https://github.com/glossarist/convert.glossarist.org/issues/3

**Comment by ribose-jeffreylau** [comment]
https://convert.paneron.org is now fully operational.
